@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.dubhe.anvilcraft.advancements.criteron;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;